[package]
name = "kore_companion"
version = "0.9.0"
description = "K.O.R.E. Companion"
authors = ["Cello Z."]
edition = "2021"

[lib]
name = "kore_companion_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }
swift-rs = "1"

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-deep-link = "2"
dotenvy = "0.15"
urlencoding = "2.1"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serialport = "4.7"
tiny_http = "0.12"

[target.'cfg(target_os = "macos")'.dependencies]
macos-accessibility-client = "0.0.1"
